# Consulting services

[[footer]]
name = 'Consulting Services'
pageRef = "/capabilities"
weight = 10

[[footer]]
name = 'Azure DevOps Migration'
parent = 'Consulting Services'
pageRef = "/capabilities/azure-devops-migration-services"
weight = 10

[[footer]]
name = 'DevOps Technology Consultancy'
parent = 'Consulting Services'
pageRef = "/capabilities/devops-technology-consultancy"
weight = 20

# Mentoring services

[[footer]]
name = 'Mentoring Services'
pageRef = "/capabilities/mentor-programs"
weight = 20

[[footer]]
name = 'Product Development Mentoring Program'
parent = 'Mentoring Services'
pageRef = "/capabilities/mentor-programs/product-development-mentoring-program"
weight = 10

[[footer]]
name = 'Product Management Mentor Program'
parent = 'Mentoring Services'
pageRef = "/capabilities/mentor-programs/product-development-mentoring-program"
weight = 20
